baseurl: ""
url: "https://chengrui310.github.io"

title: Cheng Rui
email: your_email@example.com
description: Personal academic homepage

markdown: kramdown
plugins:
  - jekyll-email-protect

collections:
  - publications
  - news
